# Generated by Django 5.1.3 on 2024-12-25 16:28

import commits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='id',
            field=models.CharField(default=commits.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.CharField(default=commits.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
