# Generated by Django 5.1.3 on 2024-12-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0002_alter_commit_id_alter_module_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter')], max_length=10),
        ),
        migrations.AlterField(
            model_name='modulecommit',
            name='file_path',
            field=models.CharField(max_length=200),
        ),
    ]
