# Generated by Django 5.1.3 on 2024-12-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0003_alter_commit_semester_alter_modulecommit_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='department',
            field=models.CharField(max_length=200),
        ),
    ]
