# Generated by Django 5.1.3 on 2024-12-25 16:52

import commits.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0005_alter_commit_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(default=commits.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='modulecommit',
            name='module',
        ),
        migrations.RemoveField(
            model_name='modulecommit',
            name='commit',
        ),
        migrations.CreateModel(
            name='CourseCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=200)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commits.course')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commits.commit')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='commits',
            field=models.ManyToManyField(related_name='courses', through='commits.CourseCommit', to='commits.commit'),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='ModuleCommit',
        ),
    ]
