# Generated by Django 5.1.3 on 2024-12-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0006_course_remove_modulecommit_module_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecommit',
            old_name='Course',
            new_name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
    ]
