# Generated by Django 5.1.3 on 2024-12-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0007_rename_course_coursecommit_course_course_scanned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='scanned',
        ),
        migrations.AddField(
            model_name='commit',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
    ]
