# Generated by Django 5.1.3 on 2024-12-28 10:20

import commits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0008_remove_course_scanned_commit_scanned'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.CharField(default=commits.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('enLabel', models.CharField(max_length=200)),
                ('deLabel', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(related_name='courses_programs', to='commits.studyprogram'),
        ),
    ]
