# Generated by Django 5.1.3 on 2024-12-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0010_remove_course_department_course_abbrev_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='recommended_semester',
            field=models.CharField(default='Both', max_length=10),
        ),
    ]
